"""
This type stub file was generated by cyright.
"""

from typing import Any
from .context import Context

class Runtime:
    """
    Represents a JavaScript runtime corresponding to an
    object heap. Several runtimes can exist at the same time but they
    cannot exchange objects. Inside a given runtime, no multi-threading is
    supported.
    """
    def __init__(self) -> None:
        ...
    
    def set_memory_limit(self, limit: int) -> Any:
        ...
    
    def set_max_stack_size(self, max_stack_size: int) -> Any:
        ...
    
    @property
    def dump_flags(self): # -> unsigned long long:
        ...
    
    @dump_flags.setter
    def dump_flags(self, flags: int): # -> None:
        ...
    
    @property
    def gc_threshold(self): # -> size_t:
        ...
    
    @gc_threshold.setter
    def gc_threshold(self, gc_threshold: int): # -> None:
        ...
    
    def compute_memory_usage(self) -> Any:
        """C Equivilent to JS_ComputeMemoryUsage(...) but returns a 
        MemoryUsage cython class instead of a struct."""
        ...
    
    def dump_memory_usage(self, filename: object) -> None: # -> None:
        ...
    
    def update_statck_top(self) -> Any:
        ...
    
    def context(self) -> context:
        """creates a new Javascript context"""
        ...
    


